"""
Django settings for agent_jobs_shell project.

Generated by 'django-admin startproject' using Django 2.2.2.

For more information on this file, see
https://docs.djangoproject.com/en/2.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.2/ref/settings/
"""

from .base_settings import *

SECRET_KEY = 'ycx_89&vi)2p!sem46w&pg83tcam0y!r-1-s@o1k$!0gsum@9#'

DEBUG = True

INSTALLED_APPS += [
    'agent_jobs_shell.shell',
]

# Database
# https://docs.djangoproject.com/en/2.2/ref/settings/#databases

DATABASES = {
    **DATABASES,
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}
